/*This file is automatically generated from a Keras model*/

#ifndef RNN_DATA_H
#define RNN_DATA_H

#include "rnn.h"

#define DENSE_1_SIZE 16
extern const DenseLayer dense_1;

#define GRU_1_SIZE 16
extern const GRULayer gru_1;

#define DENSE_2_SIZE 5
extern const DenseLayer dense_2;

struct RNNState {
  float gru_1_state[GRU_1_SIZE];
};


#endif
